# Generated by Django 4.2 on 2024-07-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president_name', models.CharField(max_length=400)),
                ('president_image', models.ImageField(null=True, upload_to='Picture/')),
                ('secretary_name', models.CharField(max_length=400)),
                ('secretary_image', models.ImageField(null=True, upload_to='media/')),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
    ]
