# Generated by Django 4.2 on 2024-07-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotaryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeCoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
