# Generated by Django 4.2 on 2024-07-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotaryapp', '0002_homecoverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='president_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='history',
            name='secretary_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
